name: Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthbuild/actions-setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-cache: false
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      # Check if Generated Go files are up to date
      - name: GO proto up-to-date
        run: |
          earthly --ci +proto
          if ! git diff --quiet; then
            echo "Generated Go files are not up to date"
            git diff --stat
            exit 1
          fi
        # LINT
      - name: Lint Proto
        run: earthly --ci +lint-proto
      - name: Lint Migrate
        run: earthly --ci +lint-migrate
      - name: Lint GO
        run: earthly --ci +lint-go
        # TEST
      - name: Test Unit
        run: earthly --ci +test-unit
      - name: Test Integration
        env:
          EARTHLY_SECRET_FILES: google_account_key=google_account_key.json
        run: |
          echo ${{ secrets.GOOGLE_ACCOUNT_KEY }} | base64 -d > google_account_key.json
          earthly --ci --allow-privileged \
            --secret aws_access_key_id=${{  secrets.AWS_ACCESS_KEY_ID }} \
            --secret aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
             \
            +test-integration
